version: '2'
services:
  vindas-app:
    image: vindas
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://vindas-mysql:3306/vindas?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://vindas-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://vindas-elasticsearch:9200
      - KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=vindas
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_PRODUCER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - KAFKA_PRODUCER_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
    ports:
      - 8084:8084
  vindas-mysql:
    extends:
      file: mysql.yml
      service: vindas-mysql
  vindas-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: vindas-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
